package com.xiangxun.atms.common.install;



/**
 * <h2>常用的常量定义</h2>
 * <p>Description: 简单的常量定义类</p>
 * @version 1.0
 */
public final class CheckConstant
{

	//ITMS 主库数据库结构
	
    public final static String ITMS_TRIGGER [] = {};
    
	public final static String ITMS_PROCEDURE [] = {};
	
	public final static String ITMS_PACKAGE [] = {};
	
	public final static String ITMS_PACKAGEBODY [] = {};
	
	public final static String ITMS_TABLE [] = {
		"SYS_VIDEO_INFO",
		"SYS_VIDEOADDRESS_INFO",
		"SYS_VERSION_NOTE",
		"SYS_USER_SKIN",
		"SYS_USER_ROLE",
		"SYS_USER_DESKTOP_MENU",
		"SYS_USER_DESK",
		"SYS_USER_DATA_AUTHORITY",
		"SYS_USER",
		"SYS_ROLE_RESOURCES",
		"SYS_ROLE",
		"SYS_ROAD_INFO",
		"SYS_ROAD_DEVICE_DEPT",
		"SYS_RETRIEVE_INFO",
		"SYS_RESOURCE",
		"SYS_POLICE_USER",
		"SYS_POLICE_CAR",
		"SYS_PICMIXTURE_INFO",
		"SYS_PARAMS",
		"SYS_ORG",
		"SYS_OPER_LOG",
		"SYS_LOGIN_LOG",
		"SYS_FTP_INFO",
		"SYS_DIC",
		"SYS_DEVICE_TYPE",
		"SYS_DEVICE_STATUS_LOG",
		"SYS_DEVICE_STATUS_HOUR",
		"SYS_DEVICE_STATUS_DAY",
		"SYS_DEVICE_PICMIX",
		"SYS_DEVICE_LOGINFO",
		"SYS_DEVICE_INFO",
		"SYS_DEVICE_GROUP",
		"SYS_DEVICE_DIRECT_SPEED",
		"SYS_DEVICETYPE_INFO",
		"SYS_DEVICEMAINTAIN_INFO",
		"SYS_DEVICEGROUP_INFO",
		"SYS_DEVICECOMPANY_INFO",
		
		"SMS_VIOTEMPLET_INFO",
		"SMS_TEMPLET_INFO",
		"SMS_SUBSCRIBE_LOG",
		"SMS_SENDTASK_INFO",
		"SMS_SENDLOG_INFO",
		"SMS_RECEIVE_INFO",
		"SMS_RECEIVEBLACK_INFO",
		"SMS_ORDER_LOG",
		"SMS_ORDERTYPE_INFO",
		"SMS_GROUP_INFO",
		"SMS_CONTACT_INFO",
		"SMS_CONTACT_GROUP",
		
		"SIGNAL_TIMEWORK_INFO",
		"SIGNAL_PRECINCTSCHEME_INFO",
		"SIGNAL_LAMP_INFO",
		"SIGNAL_GREENSCHEME_INFO",
		"SIGNAL_GREENSCHEME_CROSSTIME",
		"SIGNAL_FLOWDEVICE_INFO",
		"SIGNAL_FLOWDEVICE_DATE",
		"SIGNAL_CROSSROADS_INFO",
		"SIGNAL_CONTROL_INFO",
		"SIGNAL_CONTROL_CROSSROAD",
		"SIGNAL_AREAS_INFO",
		
		"PAS_ROAD_PASSPORT",
		"PAS_ROAD",
		"PAS_PASSPORT_INFO_HIS",
		"PAS_PASSPORT_INFO",
		
		"PARKINGLOT_PARK_DATA",
		"PARKINGLOT_LEADDEVICE_INFO",
		"PARKINGLOT_INFO",
		"PARKINGLOT_EQUIP",
		
		"OCCUPY_SPECIAL_INFO",
		"OCCUPY_SCORE_MANAGE",
		"OCCUPY_RULER_INFO",
		"OCCUPY_PICTURE_INFO",
		"OCCUPY_LEVEL_INFO",
		"OCCUPY_INSPECT_INFO",
		"OCCUPY_ICON_INFO",
		"OCCUPY_DELAY_INFO",
		"OCCUPY_BUILDER_INFO",
		"OCCUPY_BLACK_MANAGE",
		"OCCUPY_APPLY_INFO",
		"OCCUPY_ADVISETEMPLET_INFO",
		
		"LEDSHOW_TIMECONTENT_INFO",
		"LEDSHOW_TEXTCONTENT_INFO",
		"LEDSHOW_TERMINAL_PROGRAM",
		"LEDSHOW_TERMINAL_INFO",
		"LEDSHOW_TERMINALGROUP_INFO",
		"LEDSHOW_RELEASEJOB_INFO",
		"LEDSHOW_PUBLISH_LOG",
		"LEDSHOW_PROGRAM_INFO",
		"LEDSHOW_PROGRAMGROUP_INFO",
		"LEDSHOW_CONTROL_LOG",
		
		"JTSS_VEHICLEDETECTOR_ROAD",
		"JTSS_VEHICLEDETECTOR_HIS",
		"JTSS_VEHICLEDETECTOR",
		"JTSS_TRAFFIC_ROAD",
		"JTSS_TRAFFIC_IMAGE",
		"JTSS_TRAFFICSIGNS_INFO",
		"JTSS_TRAFFICSIGNS_HIS",
		"JTSS_TRAFFICSIGNS",
		"JTSS_SHORTROADMARKING_HIS",
		"JTSS_SHORTROADMARKING",
		"JTSS_LONGROADMARKING_HIS",
		"JTSS_LONGROADMARKING",
		"JTSS_ISOLATIONFACILITIES_IMAGE",
		"JTSS_ISOLATIONFACILITIES_HIS",
		"JTSS_ISOLATIONFACILITIES",
		"JTSS_AUDIBLEALERTDEVICE_ROAD",
		"JTSS_AUDIBLEALERTDEVICE_HIS",
		"JTSS_AUDIBLEALERTDEVICE",
		
		"EMERGENCY_UNIT",
		"EMERGENCY_TEAM",
		"EMERGENCY_PROFICIENT",
		"EMERGENCY_PLANS_VERSIONS",
		"EMERGENCY_PLANS_VERIFYS_VERS",
		"EMERGENCY_PLANS_VERIFYS",
		"EMERGENCY_PLANS_ITEM_VERS",
		"EMERGENCY_PLANS_ITEM",
		"EMERGENCY_PLANS_DOC",
		"EMERGENCY_PLANS_ATTR_VERS",
		"EMERGENCY_PLANS_ATTR",
		"EMERGENCY_PLANS",
		"EMERGENCY_MATERIAL",
		"EMERGENCY_INTELLECTUAL",
		"EMERGENCY_FILE_INFO",
		"EMERGENCY_DUTY",
		"EMERGENCY_CATALOG_INFO",
		"EMERGENCY_CASE",
		"EMERGENCY_CAR",
		"EMERGENCY_ATTACH_INFO"
	};
	
	
	
    //CROSS 主库数据库结构
	
    public final static String CROSS_TRIGGER [] = {
    	"CROSS_T_RECORDLIST_PROCESS",
    	"CROSS_T_RECORDLIST_DATACOPY",
    	"CROSS_T_ALARMLIST_HISCOPY"
    	};
    
	public final static String CROSS_PROCEDURE [] = {
		"CROSS_RECORDLIST_TEMPDEL",
		"CROSS_RECORDLIST_ITABLE",
		"CROSS_RECORDLIST_CTABLEDIY",
		"CROSS_RECORDLIST_CTABLE",
		"CROSS_ALARMLIST_HISMOVE"
		};
	
	public final static String CROSS_PACKAGE [] = {
		"PACK_RECORDLIST_PROCESS"
	};
	
	public final static String CROSS_PACKAGEBODY [] = {
		"PACK_RECORDLIST_PROCESS"
	};
	
	//已去除自增表
	public final static String CROSS_TABLE [] = {
		"VIO_VIPNAME",
		"VIO_TYPE",
		"VIO_RECORD_TEMP",
		"VIO_RECORD_LIST",
		"VIO_MARKER_TYPE",
		"VIO_LIST_HCJX",
		"VIO_LIMIT_RULE",
		"VIO_LIMIT_ROADDEVICE_RELATION",
		"VIO_CAR_YELLOW",
		"VIO_AREA",
		
		"TRAFFICONTROL_TEMP_INFO",
		"TRAFFICONTROL_SINGLE_INFO",
		"TRAFFICONTROL_AREA_INFO",
		
		"FLOW_NODES_INFO",
		"FLOW_LINKS_STATUSHIS",
		"FLOW_LINKS_STATUS",
		"FLOW_LINKS_INFO",
		"FLOW_GUIDE_PIC",
		"FLOW_GUIDE_INFO",
		"FLOW_GUIDE_DETECTOR",
		"FLOW_GUIDE_DATE",
		"FLOW_EQUIP",
		"FLOW_DETECTOR_INFO",
		"FLOW_DETECTOR_DATE",
		"FLOWST_TRAFFINFO",
		"FLOWST_ROADSTATUS",
		"FLOWST_POSCONF",
		"FLOWST_NODES",
		"FLOWST_LINKS_POSCONF",
		"FLOWST_LINKS",
		
		"CROSS_RECORD_VIP_PASS",
		"CROSS_RECORD_SUSPICION_TAOPAI",
		"CROSS_RECORD_SUSPICION_OTHER",
		"CROSS_RECORDLIST_TEMP",
		"CROSS_RECORDLIST_MADESELF",
		"CROSS_JOB_EXCEPTION",
		"CROSS_DEVICE_STATUS",
		"CROSS_COUNT_MONTH",
		"CROSS_BLACK_INFO",
		"CROSS_BLACK_HIS",
		"CROSS_BLACK_ALARMHIS",
		"CROSS_BLACK_ALARM",
		
		"BLACKTYPECOLOR",
		
		"ANALYSIS_VIO_COUNT_MONTH",
		"ANALYSIS_VIO_COUNT_DAYS",
		"ANALYSIS_CROSS_NOLOCAL_MONTH",
		"ANALYSIS_CROSS_NOLOCAL_DAYS",
		"ANALYSIS_CROSS_FLOW_MONTH",
		"ANALYSIS_CROSS_FLOW_DAYS",
		"ANALYSIS_CROSS_BLACK_MONTH",
		"ANALYSIS_CROSS_BLACK_DAYS"
	};
	
	
    //GPS 主库数据库结构
	
    public final static String GPS_TRIGGER [] = {};
    
	public final static String GPS_PROCEDURE [] = {
		"PROC_STATION_OUTSID_TIMES",
		"PROC_OM_GPS_COMPARE_RT",
		"PROC_OM_GPS_COMPARE"
	};
	
	public final static String GPS_PACKAGE [] = {};
	
	public final static String GPS_PACKAGEBODY [] = {};
	
	//已去除自增表
	public final static String GPS_TABLE [] = {
		"T_ANALYSIS",
		"OM_STATION_TEMPLATE",
		"OM_STATION_RECORDTIME",
		"OM_STATION_MANAGER",
		"OM_ORG_TEMP",
		"OM_ORDER_RECESS_USER",
		"OM_ORDER_MANAGER_USER",
		"OM_ORDER_MANAGER_CAR",
		"OM_ORDER_MANAGER",
		"OM_INSPECT_STATION",
		"OM_GPS_COMPARE_RT",
		"OM_CAST_STATION",
		"OM_BASE_ORDER_TYPE",
		"OM_BASE_GIS_TYPE",
		"GPS_REALTIME_ISEXTENT",
		"GPS_REALTIME",
		"GPS_OM_COMPARE",
		"GPS_OM_ALARM_TIME",
		"GPS_ALARM_GUARD"
	};
} 
