MapFactory.Define("ItmsMap/MapConfig",
	["MapFactory/MapConfigAPI*"],
	function(api){
		var serviceUrl = arcgisbaseurl+"/rest/services/",
			initExtent = maxExtent,
			resolutions = [],
			spatialReference = 4326,
			projectSpatialReference = 32649,
			referenceCSS = [
				"/ThirdParty/ArcgisLib/js/esri/css/esri.css",
				"/ThirdParty/ArcgisLib/js/dojo/dijit/themes/claro/claro.css"
			];
		
		if(arcgisResolutions)resolutions = arcgisResolutions;
		var layers = {
			baseMap : {name:"底图",url:serviceUrl+"itms/baseMap/MapServer",id:"baseMap",allowOperation:false},
			geometryService : {name:"几何服务",url:serviceUrl+"Geometry/GeometryServer",id:"geometryService"},
			serviceAreaRest : {name:"服务区服务",url:serviceUrl+"/atms/xianMapExtentionFunction/NAServer/Service%20Area",id:"serviceAreaRest"},
			positionLayer : {name:"定位图层",id:"positionLayer",isTop:true},
			positionHighLightLayer : {name:"定位高亮图层",id:"positionHighLightLayer",isTop:true},
			buffer : {name:"缓冲区分析服务",url:serviceUrl+"Geometry/GeometryServer/buffer",id:"buffer"},
			union : {name:"几何体合并服务",url:serviceUrl+"Geometry/GeometryServer/union",id:"union"},
			route : {name:"路径分析地址",url:serviceUrl+"itms/roadNet/NAServer/Route",id:"route"},
			closedpoint : {name:"投影点查询",url:serviceUrl+"itms/roadNet/NAServer/Route",id:"closedpoint"},
			queryResult : {name:"查询结果",id:"queryResult"},
			position : {name:"位置图层",id:"position"},
			unStart : {name:"未开工图层",id:"occupyUnstart"},
			constructing : {name:"施工中图层",id:"occupyConstruct"},
			maturring : {name:"快到期图层",id:"occupyMaturring"},
			defferring : {name:"已延期图层",id:"occupyDeffering"},
			done : {name:"已完工图层",id:"occupyDone"},
			matured: {name:"已超期图层",id:"occupyMatured"},
			baseRoad : {name:"道路图层",url:serviceUrl+"itms/xiangxun/MapServer/0",id:"baseRoad"},
			cross : {name:"卡口图层",url:serviceUrl+"itms/xiangxun/MapServer/1",id:"cross"},
			crossAnalyLayer : {name:"卡口分析",id:"crossAnalyLayer"},
			crossAnalyBarriersLayer : {name:"卡口障碍物",id:"crossAnalyBarriersLayer"},
			crossAlarm : {name:"卡口报警",url:serviceUrl+"itms/xiangxun/MapServer/1",id:"crossAlarm"},
			flow : {name:"流量图层",url:serviceUrl+"itms/xiangxun/MapServer/5",id:"flow"},
			flowDevice : {name:"流量检测器",url:serviceUrl+"itms/xiangxun/MapServer/3",id:"flowDevice"},
			flowPanel : {name:"流量诱导屏",url:serviceUrl+"itms/xiangxun/MapServer/4",id:"flowPanel"},
			gpsextent : {name:"GPS电子围栏",url:serviceUrl+"itms/xiangxun/MapServer/26",id:"gpsextent"},
			occupyPolygon : {name:"挖占面",url:serviceUrl+"itms/xiangxun/MapServer/8",id:"occupyPolygon"},
			signal : {name:"信号机",url:serviceUrl+"itms/xiangxun/MapServer/25",id:"signal"},
			educationPOI : {name:"教育机构",url:"itms/xiangxun/MapServer/34",id:"educationPOI"},
			orgPOI : {name:"行政区面",url:"itms/xiangxun/MapServer/27",id:"orgPOI"},
			townsPOI : {name:"乡镇点",url:serviceUrl+"itms/xiangxun/MapServer/29",id:"townsPOI"},
			governmentPOI : {name:"行政单位",url:serviceUrl+"itms/xiangxun/MapServer/36",id:"governmentPOI"},
			enterprisePOI : {name:"企事业单位",url:serviceUrl+"itms/xiangxun/MapServer/30",id:"enterprisePOI"},
			publicPOI : {name:"公共场所",url:serviceUrl+"itms/xiangxun/MapServer/31",id:"publicPOI"},
			hospitalPOI : {name:"医疗卫生",url:serviceUrl+"itms/xiangxun/MapServer/33",id:"hospitalPOI"},
			tourismPOI : {name:"旅游景点",url:serviceUrl+"itms/xiangxun/MapServer/35",id:"tourismPOI"},
			marketPOI : {name:"超市广场",url:serviceUrl+"itms/xiangxun/MapServer/37",id:"marketPOI"},
			petrolFillPOI : {name:"加油站",url:serviceUrl+"itms/xiangxun/MapServer/32",id:"petrolFillPOI"},
			mapSigns : {name:"标绘图层",id:"mapSigns"},
			omPoint : {name:"勤务点服务",url:serviceUrl+"itms/xiangxun/MapServer/14",id:"omPoint"},
			omPolyline : {name:"勤务线服务",url:serviceUrl+"itms/xiangxun/MapServer/15",id:"omPolyline"},
			omPolygon : {name:"勤务面服务",url:serviceUrl+"itms/xiangxun/MapServer/16",id:"omPolygon"},
			omStationLayer : {name:"岗位层",id:"mapOMStationLayer"},
			omStationExtentsLayer : {name:"巡查面",id:"mapOMStationExtentsLayer"},
			omUnorderedLayer : {name:"未排班",id:"omUnorderedLayer"},
			omPoliceLayer : {name:"警员",id:"mapOMPoliceLayer"},
			tempPlayerLayer : {name:"轨迹回放车辆",id:"tempPlayerLayer"},
			crossHistoryLayer : {name:"轨迹回放路径",id:"crossHistoryLayer"},
			gps : {name:"GPS图层",id:"gps"},
			gpsHistoryLayer : {name:"GPS历史轨迹",id:"gpsHistoryLayer"},
			videoLayer : {name:"视频设备",url:serviceUrl+"itms/xiangxun/MapServer/38",id:"videoLayer"},
			vioLayer : {name:"违法设备",id:"vioLayer"},
			dirParking : {name:"直属停车场",id:"dirParking"},
			genParking : {name:"停车场",id:"genParking"},
			leadDevice : {name:"停车场诱导屏",id:"leadDevice"},
			preplanPoint : {name:"预案点",url:serviceUrl+"itms/xiangxun/MapServer/10",id:"preplanPoint"},
			preplanPolyline : {name:"预案线",url:serviceUrl+"itms/xiangxun/MapServer/11",id:"preplanPolyline"},
			preplanPolygon : {name:"预案面",url:serviceUrl+"itms/xiangxun/MapServer/12",id:"preplanPolygon"},
			traffic_point : {name:"交通设施点",url:"",id:"traffic_pointlayer"},
			traffic_polygon : {name:"交通设施面",url:"",id:"traffic_polygonlayer"},
			bindedPreplanLayer : {name:"已绑定",id:"bindedPreplanLayer"},
			passLayer: {name: "通行证图层", id: "passportresult"},
			threeDimension: {name: "三维标注图层", id: "Label3D"},
			roadMaintenance : {name:"道路维护",id:"roadMaintenance"}
		};
		return eval(MapFactory.GenerateAPI(api));
	}
);